name: humiview
description: "HumiView — Precision Environmental Monitoring for Healthcare"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  flutter_animate: ^4.5.2
  intl: ^0.20.1
  shimmer: ^3.0.0
  go_router: ^17.3.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_padded.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_padded.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo_circle.png"
  android_12:
    image: "assets/images/logo_padded.png"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_circle.png
